groups:

  - name: cloudops-alerts

    rules:

      # =========================================
      # HIGH HTTP ERROR RATE
      # =========================================

      - alert: HighHTTPErrorRate

        expr: |
          (
            sum(rate(cloudops_http_requests_total{status_code=~"5.."}[1m]))
            /
            sum(rate(cloudops_http_requests_total[1m]))
          ) * 100 > 5

        for: 30s

        labels:
          severity: critical
          service: cloudops-server

        annotations:
          summary: "High HTTP error rate detected"

          description: |
            HTTP 5xx error rate is above 5% for more than 30 seconds.

          runbook: "Investigate CloudOps server logs and recent deployments."


      # =========================================
      # HIGH CPU
      # =========================================

      - alert: HighContainerCPU

        expr: |
          (
            sum by (name) (
              rate(container_cpu_usage_seconds_total{name!=""}[1m])
            ) * 100
          ) > 80

        for: 1m

        labels:
          severity: warning
          service: docker

        annotations:
          summary: "High container CPU usage"

          description: |
            Container {{ $labels.name }} CPU usage is above 80%.


      # =========================================
      # HIGH MEMORY
      # =========================================

      - alert: HighContainerMemory

        expr: |
          (
            container_memory_usage_bytes{name!=""}
            /
            container_spec_memory_limit_bytes{name!=""}
          ) * 100 > 80

        for: 1m

        labels:
          severity: warning
          service: docker

        annotations:
          summary: "High container memory usage"

          description: |
            Container {{ $labels.name }} memory usage is above 80%.
