apiVersion: v1
kind: Namespace
metadata:
  name: cloudops
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudops-backend
  namespace: cloudops
  labels:
    app: cloudops-backend
    tier: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudops-backend
  template:
    metadata:
      labels:
        app: cloudops-backend
        tier: api
    spec:
      containers:
        - name: backend
          image: nginx:alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cloudops-backend
  namespace: cloudops
  labels:
    app: cloudops-backend
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 80
      protocol: TCP
  selector:
    app: cloudops-backend
